// AUTO-GENERATED by scripts/owner_bias.py — per-owner NFL-team fandom mined from the
// league's 2023-25 winning bids: {owner: {fan: {NFL team: bid multiplier}}}. A team makes
// the list only with 2+ seasons of evidence and either >=4 buys at >=3.5x the pool share
// or a >=$3 over-curve premium on a >=2x cluster. Positional overpay and player-loyalty
// biases were tested and are NOT real in this league (outputs/reports/owner_bias.md).
const OWNER_BIAS = {"Rohabhabibo": {"fan": {"DEN": 1.1}}, "espn14211458": {"fan": {"NE": 1.12}}, "espn98580191": {"fan": {"TEN": 1.09}}, "eyedocjj": {"fan": {"ARI": 1.05}}, "funblood": {"fan": {"GB": 1.23}}, "kdoggs80": {"fan": {"MIN": 1.14, "TB": 1.05}}, "silverandblack.27": {"fan": {"LV": 1.3}}};
