// AUTO-GENERATED by scripts/depth_takeover_study.py — RB takeover targets 2026.
// Backups with stable/improving Kalman true skill blocked by a fading-skill workload
// leader. Validated (2011-24, n=236 RB pairs): backup close-or-better in skill ->
// 58% takeover rate vs 27% when starter clearly better; 40% vs 15% with starter
// injuries removed (pure healthy benching/phase-out). RB-only: the healthy signal
// dies at WR/TE (roles too sticky) and QB (no signal, tiny samples).
const TAKEOVER_2026 = {
  "Zach Charbonnet": {blk: "Kenneth Walker III (SEA)", gap: -0.18, tb: "+0.08", ts: "-0.05",
    why: "Out-skills Walker outright (-0.18z gap) and already at 185 plays to Walker's 221 — the cleanest case on the board"},
  "Tank Bigsby": {blk: "Saquon Barkley (PHI)", gap: -0.14, tb: "+0.16", ts: "-0.21",
    why: "Saquon fading hard (-0.21 trend at 28, post-482-touch season); Bigsby rising +0.16"},
  "Brian Robinson": {blk: "Christian McCaffrey (SF)", gap: 0.03, tb: "+0.04", ts: "-0.23",
    why: "CMC's per-play edge is gone (avg skill, -0.23 trend, age 29+); B-Rob stable at even skill"},
  "Rachaad White": {blk: "Bucky Irving (TB)", gap: -0.11, tb: "+0.32", ts: "-0.58",
    why: "White rebounded +0.32 while Irving crashed -0.58 (injury-tinged — softest of the four)"},
};
