"""
AUCTION TIMING — when do bargains fall in THIS league's auctions?

espn_drafts.csv has the nomination order (overall_pick) and every winning bid,
2023-2025. Price every non-keeper skill buy against same-season FFA AAV
(nflv_ffa_league) and ask: by draft PHASE, does the league over- or under-pay?

  paid_ratio = paid / max(aav, 1)   (players missing AAV excluded; $1 buys of
  sub-$1-AAV players excluded from ratios - the $1 floor distorts them)

Phases: nominations 1-30 (opening frenzy), 31-60, 61-90, 91-120, 121+ (endgame).
Also: per-position phase curves, the $ remaining in the room by phase, and the
per-phase share of "bargains" (paid <= 0.8x AAV) among $5+ AAV players.

Output: outputs/reports/auction_timing.md
"""
import os, csv, re
import numpy as np, pandas as pd
import sqlite3

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
norm = lambda s: re.sub(r"\s+", " ", re.sub(r"\b(jr|sr|ii|iii|iv|v)\b", "",
                        re.sub(r"[^a-z ]", "", str(s).lower()))).strip()

dr = pd.read_csv(os.path.join(ROOT, "outputs", "espn_drafts.csv"))
dr["kept"] = dr.keeper.astype(str).str.lower().isin(["true", "1"])
dr["bid"] = pd.to_numeric(dr.bid, errors="coerce").fillna(0)
dr["nm"] = dr.player.map(norm)

con = sqlite3.connect(os.path.join(ROOT, "db", "nfl_odds.db"))
ffa = pd.read_sql("""SELECT season, player nm_raw, ffa_aav FROM nflv_ffa_league
                     WHERE ffa_aav IS NOT NULL""", con)
con.close()
ffa["nm"] = ffa.nm_raw.map(norm)
ffa = ffa.drop_duplicates(["season", "nm"])
dr = dr.merge(ffa[["season", "nm", "ffa_aav"]], on=["season", "nm"], how="left")

d = dr[(~dr.kept) & dr.pos.isin(["QB", "RB", "WR", "TE"])].copy()
# nomination order within each season (keepers occupy early "picks"; rank the real ones)
d["nom"] = d.groupby("season")["overall_pick"].rank(method="first")
PHASES = [(1, 30), (31, 60), (61, 90), (91, 120), (121, 999)]
d["phase"] = pd.cut(d.nom, [0, 30, 60, 90, 120, 999],
                    labels=["1-30", "31-60", "61-90", "91-120", "121+"])

_out = []
def pr(*a): s = " ".join(str(x) for x in a); _out.append(s); print(s)

pr(f"non-keeper skill buys 2023-25: n={len(d)}, AAV matched {d.ffa_aav.notna().mean():.0%}\n")

# ratio universe: AAV >= 2 so the $1 floor doesn't manufacture fake bargains
r = d[(d.ffa_aav >= 2)].copy()
r["ratio"] = r.bid.clip(lower=1) / r.ffa_aav
pr("PAID / AAV by nomination phase (AAV>=$2):")
pr(f"{'phase':>8s} {'n':>4s} {'median':>7s} {'mean':>6s} {'bargain%':>9s}   (bargain = paid <= 0.8x AAV, AAV >= $5)")
for ph in ["1-30", "31-60", "61-90", "91-120", "121+"]:
    g = r[r.phase == ph]
    b = g[g.ffa_aav >= 5]
    pr(f"{ph:>8s} {len(g):4d} {g.ratio.median():7.2f} {g.ratio.mean():6.2f} "
       f"{(b.ratio <= 0.8).mean():8.0%}   (n_b={len(b)})")

pr("\nby position x phase (median paid/AAV, AAV>=$2; n in parens):")
pv = r.pivot_table(index="pos", columns="phase", values="ratio", aggfunc="median", observed=True).round(2)
cn = r.pivot_table(index="pos", columns="phase", values="ratio", aggfunc="count", observed=True)
for pos in ["QB", "RB", "WR", "TE"]:
    if pos not in pv.index: continue
    pr(f"  {pos}: " + "  ".join(f"{ph}={pv.loc[pos, ph]:.2f}({int(cn.loc[pos, ph])})"
                                for ph in pv.columns if pd.notna(pv.loc[pos, ph])))

# money drain: cumulative % of total auction $ spent by phase
pr("\nmoney drain (cumulative % of the season's auction $ spent):")
for season, g in d.groupby("season"):
    g = g.sort_values("nom"); cum = g.bid.cumsum() / g.bid.sum()
    marks = {ph: cum[g.nom <= hi].iloc[-1] if (g.nom <= hi).any() else np.nan
             for ph, (_, hi) in zip(["1-30", "31-60", "61-90", "91-120"], PHASES[:4])}
    pr(f"  {season}: " + "  ".join(f"after {ph}: {v:.0%}" for ph, v in marks.items()))

# where do the $1-3 darts get bought?
cheap = d[d.bid <= 3]
pr("\n$1-3 buys by phase: " + "  ".join(
    f"{ph}={len(cheap[cheap.phase==ph])}" for ph in ["1-30", "31-60", "61-90", "91-120", "121+"]))

# stars: when do the $40+ sales happen?
star = d[d.bid >= 40]
pr(f"$40+ sales by phase: " + "  ".join(
    f"{ph}={len(star[star.phase==ph])}" for ph in ["1-30", "31-60", "61-90", "91-120", "121+"]))

open(os.path.join(ROOT, "outputs", "reports", "auction_timing.md"), "w", encoding="utf-8").write(
    "# Auction timing - when do bargains fall in this league?\n\n"
    "Generated by `scripts/auction_timing_study.py` from espn_drafts.csv 2023-25 priced\n"
    "against same-season FFA AAV. Phases are NOMINATION ORDER within each auction.\n\n```\n"
    + "\n".join(_out) + "\n```\n")
print("\nwrote outputs/reports/auction_timing.md")
