"""
🚩 negative-news August flags for the draft tool.

The tone study (outputs/reports/tone_signal.md) found ONE actionable draft signal in
GDELT tone: a priced player whose August news volume SPIKES (top-20% spike vs his own
Jan-May baseline) with NEGATIVE tone (< -1) averages -20 VORP vs price peers — the
holdout / injury / suspension pattern (Charles '16, Keenan '16, Golladay '20,
Fournette + McCoy '18, Etienne '24, Ekeler '25). One-sided: a red flag, not a buy signal.

DRAFT WEEK WORKFLOW (late August):
  python scripts/fetch_gdelt_bq.py fetch --start 2026 --end 2026   (~15 GB, free tier)
  python scripts/build_news_flags.py                                (writes the JS map)
Partial-August months are fine — tone is an average and the spike uses a volume floor.

Writes docs/gdelt_flags_2026.js (+ outputs/draft_tool mirror):
  const NEWS_FLAGS = {norm_name: {t: aug_tone, s: vol_spike, n: articles}};
The spike threshold is calibrated as the 80th percentile of the 2016-25 PRICED-pool
August spikes (fixed number, so a thin flag year can't lower the bar).
"""
import argparse, json, os, re, sqlite3
import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
norm = lambda s: re.sub(r"\s+", " ", re.sub(r"\b(jr|sr|ii|iii|iv|v)\b", "",
                        re.sub(r"[^a-z ]", "", str(s).lower()))).strip()

ap = argparse.ArgumentParser()
ap.add_argument("--year", type=int, default=2026)
ap.add_argument("--dry", action="store_true", help="print flags, do not write files")
a = ap.parse_args()

con = sqlite3.connect(os.path.join(ROOT, "db", "nfl_odds.db"))
gd = pd.read_sql("SELECT name, ym, articles, avg_tone FROM nflv_gdelt_bq WHERE source='gkg'", con)
gd["y"] = gd.ym.str[:4].astype(int); gd["m"] = gd.ym.str[4:].astype(int)
aug = gd[gd.m == 8].rename(columns={"articles": "aug_n", "avg_tone": "aug_tone"})[["name", "y", "aug_n", "aug_tone"]]
base = (gd[gd.m.between(1, 5)].groupby(["name", "y"]).articles.median().rename("base_n").reset_index())
sent = aug.merge(base, on=["name", "y"], how="left")
sent["spike"] = np.log((sent.aug_n + 10) / (sent.base_n.fillna(0) + 10))

# calibrate the spike bar on the 2016-25 PRICED pool (same frame as the study)
df = pd.read_pickle(os.path.join(ROOT, "outputs", "models", "late_breakout_frame.pkl"))
df = df[(df.season >= 2016) & (df.in_ffa == 1) & (df.adp_f <= 120)].copy()
df["nm"] = df.name.map(norm)
hist = df.merge(sent.rename(columns={"name": "nm", "y": "season"}), on=["nm", "season"], how="inner")
SPIKE_BAR = float(hist.spike.quantile(0.80))
print(f"spike bar (80th pct of 2016-25 priced-pool Augusts): {SPIKE_BAR:.3f}")

# flags for the target year: spike over bar, tone < -1, volume floor 30 articles —
# restricted to names on the tool's CURRENT BOARD (docs/data.js): the study cell is priced
# fantasy players, and generic-name collisions (a 'brandon johnson' with 4k crime articles)
# otherwise dominate the list
board = json.loads(open(os.path.join(ROOT, "docs", "data.js"), encoding="utf-8").read()
                   .split("const PLAYERS = ")[1].rsplit(";", 1)[0])
board_names = set(norm(p["name"]) for p in board)
yr = sent[(sent.y == a.year) & (sent.aug_n >= 30) & (sent.aug_tone < -1) & (sent.spike >= SPIKE_BAR)
          & sent.name.isin(board_names)]
flags = {r["name"]: {"t": round(r.aug_tone, 2), "s": round(r.spike, 2), "n": int(r.aug_n)}
         for _, r in yr.iterrows()}
print(f"August {a.year}: {len(flags)} flagged"
      + ("" if flags else "  (no data for that August yet — writing an empty map)"))
for nm, f in sorted(flags.items(), key=lambda kv: kv[1]["t"])[:25]:
    print(f"  🚩 {nm:<24} tone {f['t']:+.1f}  spike {f['s']:.1f}  n={f['n']}")
if a.dry:
    raise SystemExit(0)

js = ("// AUTO-GENERATED by scripts/build_news_flags.py — 🚩 negative-news August flags.\n"
      f"// August {a.year}; spike bar {SPIKE_BAR:.3f} (80th pct of 2016-25 priced Augusts),\n"
      "// tone < -1, >=30 articles. Historical cell: mean -20 VORP vs price peers (holdout/\n"
      "// injury/suspension pattern). Refresh in draft week: fetch_gdelt_bq.py then this.\n"
      f"const NEWS_FLAGS = {json.dumps(flags)};\n"
      f"const NEWS_FLAGS_YEAR = {a.year};\n")
for d in (os.path.join(ROOT, "docs"), os.path.join(ROOT, "outputs", "draft_tool")):
    open(os.path.join(d, "gdelt_flags_2026.js"), "w", encoding="utf-8").write(js)
print("wrote docs/gdelt_flags_2026.js (+ mirror)")
