"""Emit docs/crowding_2026.js — INFORMATIONAL WR2 crowding tags (no value change).
Validated (scripts/crowding_test.py): teammate target-share crowding is REAL (t=-5.1); the model
over-projects WR2s behind an alpha WR1 (>=26% share) by -0.5 PPG and under-projects WR2s behind a
modest WR1 (<=20%) by +0.5 — but the segment (~10 players/yr) is too thin to auto-correct (correction
washes out-of-sample; +CROWD features only 7/10 years). So: tag, don't reprice.
Inputs: VAC_DATA.usage (2025 target/touch shares, canonical names) + ROSTER_2026 from vacated_role.js."""
import os, json, sys
try: sys.stdout.reconfigure(encoding="utf-8")
except Exception: pass
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def jsconst(path):
    out={}
    for line in open(path,encoding="utf-8"):
        if line.startswith("const "):
            n=line.split()[1]; out[n]=json.loads(line.split("= ",1)[1].rstrip().rstrip(";").split(";")[0])
    return out
VC=jsconst(os.path.join(ROOT,"docs","vacated_role.js"))
usage=VC["VAC_DATA"]["usage"]; roster=VC.get("ROSTER_2026",{})
teams={}
for name,u in usage.items():
    if u["pos"]!="WR": continue
    tm=roster.get(name,u["tm"])
    teams.setdefault(tm,[]).append((name,u["sh"]))
out={}
for tm,ws in teams.items():
    ws.sort(key=lambda x:-x[1])
    if len(ws)<2: continue
    top_name,top=ws[0]; wr2,sh2=ws[1]
    if sh2<0.10: continue                       # WR2 must have a real role to be worth tagging
    if top>=0.26: out[wr2]={"k":"crowded","alpha":top_name,"a_sh":round(top*100),"sh":round(sh2*100),"tm":tm}
    elif top<=0.20: out[wr2]={"k":"open","alpha":top_name,"a_sh":round(top*100),"sh":round(sh2*100),"tm":tm}
crowded=[n for n,v in out.items() if v["k"]=="crowded"]; open_=[n for n,v in out.items() if v["k"]=="open"]
print(f"WR2 tags: {len(crowded)} crowded, {len(open_)} open")
for n in crowded[:8]: print(f"  crowded: {n:22s} behind {out[n]['alpha']} ({out[n]['a_sh']}%) @{out[n]['tm']}")
for n in open_[:8]:   print(f"  open:    {n:22s} top is {out[n]['alpha']} only {out[n]['a_sh']}% @{out[n]['tm']}")
js=("// AUTO-GENERATED by scripts/build_crowding_tag.py — WR2 crowding (INFORMATIONAL, no value change).\n"
    "// Validated scripts/crowding_test.py: real effect (t=-5.1), model biases -0.5/+0.5 PPG, too thin to auto-correct.\n"
    "const CROWDING_2026 = "+json.dumps(out,separators=(",",":"))+";\n")
for d in (os.path.join(ROOT,"docs"),os.path.join(ROOT,"outputs","draft_tool")):
    try: open(os.path.join(d,"crowding_2026.js"),"w",encoding="utf-8").write(js)
    except OSError: pass
print("Wrote docs/crowding_2026.js")
