#!/usr/bin/env python3
"""Bake the league-scored FFA export into docs/ffa_2026.js.

The Blend/FFA projection toggles used to require the user to manually upload the
FFA CSV in the browser -- ffaMap lived only in that browser's localStorage, so the
buttons were dead on any other PC (and after clearing site data). That is a bad
draft-night dependency: on the home PC the toggles would simply be greyed out.

This emits the same structure parseCSV() builds from an upload, so index.html can
seed ffaMap from it and the toggles work everywhere with no upload. An actual
upload still wins -- it overwrites ffaMap and persists to localStorage.

Backtest note (scratchpad blend sweep, walk-forward 2016-2025, rank-vs-finish per
season+position): pure model 0.519, blend@0.65 0.547, pure FFA 0.545. Blend beats
model significantly (p=0.0002) but NOT FFA (p=0.50), so the default FFA weight is
0.65 -- top of the plateau, while keeping the model's magnitude calibration, which
still wins on MAE (2.859 vs 2.993) and is what auction pricing needs.

    python scripts/build_ffa_js.py
"""

import csv
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data", "ffanalytics", "FFAn_league", "projections_2026_wk0.csv")
OUT = os.path.join(ROOT, "docs", "ffa_2026.js")
MIRROR = os.path.join(ROOT, "outputs", "draft_tool", "ffa_2026.js")
POS_OK = ("QB", "RB", "WR", "TE")          # parseCSV skips K/DST -- match it exactly

SUFFIX = re.compile(r"\b(jr|sr|ii|iii|iv|v)\b")


def norm(s):
    """Mirror of index.html's norm(): lowercase, drop non [a-z ], strip suffixes."""
    s = re.sub(r"[^a-z ]", "", str(s).lower())
    s = SUFFIX.sub("", s)
    return re.sub(r"\s+", " ", s).strip()


def num(v):
    try:
        f = float(v)
        return None if f != f else f
    except (TypeError, ValueError):
        return None


def ival(v):
    f = num(v)
    return None if f is None else int(f)


def board_keys():
    """(surname, pos) -> board fkey, so nickname swaps still match.

    The board calls him "Chig Okonkwo"; FFA says "Chigoziem". fkey() normalisation
    can't bridge that, so he'd silently contribute nothing in Blend/FFA mode. Only
    unambiguous surname+position hits are aliased.
    """
    path = os.path.join(ROOT, "docs", "data.js")
    if not os.path.exists(path):
        return {}
    txt = open(path, encoding="utf-8").read()
    mt = re.search(r"const PLAYERS\s*=\s*(\[.*?\]);", txt, re.S)
    if not mt:
        return {}
    idx, out = {}, {}
    for p in json.loads(mt.group(1)):
        if p.get("position") not in POS_OK:
            continue
        n = norm(p.get("name"))
        parts = n.split()
        if not parts:
            continue
        idx.setdefault((parts[-1], p["position"]), []).append(f"{n}|{p['position']}")
    for k, v in idx.items():
        if len(v) == 1:
            out[k] = v[0]
    return out


def main():
    if not os.path.exists(SRC):
        raise SystemExit(f"missing {SRC}")
    bk = board_keys()
    m = {}
    with open(SRC, encoding="utf-8-sig") as fh:
        for r in csv.DictReader(fh):
            pos = re.sub(r"[^A-Z]", "", (r.get("position") or "").upper())
            name = r.get("player") or ""
            pts = num(r.get("points"))
            if not name or pos not in POS_OK or pts is None:
                continue
            team = re.sub(r"[^A-Z]", "", (r.get("team") or "").upper()) or None
            key = f"{norm(name)}|{pos}"
            alias = bk.get((norm(name).split()[-1], pos)) if norm(name).split() else None
            rec = {
                "pts": pts,
                "adp": num(r.get("adp")),
                "tier": ival(r.get("tier")),
                "posrank": ival(r.get("position_rank")),
                "ceil": num(r.get("ceiling")),
                "floor": num(r.get("floor")),
                "unc": num(r.get("uncertainty")),
                "aav": num(r.get("aav")),
                "team": team,
            }
            m[key] = rec
            if alias and alias != key:
                m[alias] = rec        # e.g. "chigoziem okonkwo|TE" -> also "chig okonkwo|TE"
                print(f"  [alias] {key} -> {alias}")

    body = json.dumps(m, separators=(",", ":"), sort_keys=True)
    js = ("// GENERATED by scripts/build_ffa_js.py -- do not edit.\n"
          "// League-scored FFA consensus, baked so the Blend/FFA toggles work with no upload.\n"
          f"const FFA_BAKED = {body};\n")
    for path in (OUT, MIRROR):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(js)
    print(f"wrote {len(m)} players -> {os.path.relpath(OUT, ROOT)} ({len(js)/1024:.0f} KB)")


if __name__ == "__main__":
    main()
