"""
2026 contract status for the draft board — flags walk-year (contract-year) and just-signed players
and emits a small, VALIDATED per-game value bump (docs/contract_status.js).

Signal validated in scripts/contract_year_mae.py: a walk-year feature improves out-of-sample
projection MAE (coef ~+1.4 PPG, stable, full-panel MAE -1.7%, never hurt in 9 backtests). We apply
a SHRUNK (~0.6x), position-weighted bump from the in-sample position effects (RB +1.53 / QB +1.05 /
WR +0.91 / TE +0.54) — because the walk-subset gains were noisy year to year.

Status from OverTheCap contracts (nfl_data_py): using each player's contract that covers 2026,
  final year of a MULTI-YEAR deal (years>=2)  -> WALK (contract year; apply the bump). Requiring
      years>=2 matches the validated signal (playing out a real deal) and drops 1-year stopgaps.
  signed 2026, multi-year deal                -> FADE (just paid; informational tag, bump 0 — the
      post-contract letdown is real in the event study but NOT yet MAE-validated)

Run:  python scripts/contract_status.py     (writes docs/contract_status.js + outputs/draft_tool copy)
"""
import warnings; warnings.filterwarnings("ignore")
import os, json, re
import pandas as pd
import nfl_data_py as nfl

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
norm = lambda s: re.sub(r"\b(jr|sr|ii|iii|iv|v)\b", "", re.sub(r"[^a-z ]", "", str(s).lower())).replace("  ", " ").strip()
SEASON = 2026
# shrunk (~0.6x) position-weighted walk-year bump, PPG (from in-sample position effects)
WALK_BUMP = {"QB": 0.65, "RB": 0.9, "WR": 0.55, "TE": 0.3}


def main():
    P = json.loads(open(os.path.join(ROOT, "docs", "data.js"), encoding="utf-8").read()
                   .split("const PLAYERS = ")[1].rsplit(";", 1)[0])
    pool = {}                                        # (norm name, pos) -> canonical player name
    for p in P:
        if p["position"] in ("QB", "RB", "WR", "TE"): pool[(norm(p["name"]), p["position"])] = p["name"]

    con = nfl.import_contracts()
    con = con[con["position"].isin(["QB", "RB", "WR", "TE"]) & con["years"].notna() & con["year_signed"].notna()].copy()
    con["final"] = con["year_signed"] + con["years"] - 1
    cov = con[(con["year_signed"] <= SEASON) & (con["final"] >= SEASON)].copy()      # contracts covering 2026
    # each player's operative 2026 contract = the most recently signed one that covers 2026
    cov = cov.sort_values("year_signed").groupby(["player", "position"], as_index=False).last()

    status, rows = {}, []
    for r in cov.itertuples():
        nm = pool.get((norm(r.player), r.position))
        if not nm: continue                          # not in our 2026 board pool
        if r.final == SEASON and r.years >= 2:
            bump = WALK_BUMP.get(r.position, 0.5)
            status[nm] = {"status": "walk", "bump": bump}
            rows.append((nm, r.position, "walk", bump, int(r.year_signed), int(r.years)))
        elif r.year_signed == SEASON and r.years >= 2:
            status[nm] = {"status": "fade", "bump": 0.0}
            rows.append((nm, r.position, "fade", 0.0, int(r.year_signed), int(r.years)))

    rows.sort(key=lambda x: (x[2], -x[3]))
    walks = [r for r in rows if r[2] == "walk"]; fades = [r for r in rows if r[2] == "fade"]
    print(f"WALK-year (contract-year) players in the 2026 pool: {len(walks)}  |  just-signed (FADE): {len(fades)}\n")
    print("  WALK (bump applied):")
    for nm, pos, st, bump, ys, yr in walks:
        print(f"    +{bump:>4.2f} PPG  {pos:3s} {nm[:24]:24s}  (deal {ys}, {yr}yr, ends {SEASON})")
    print("\n  FADE (tag only):")
    for nm, pos, st, bump, ys, yr in fades:
        print(f"           {pos:3s} {nm[:24]:24s}  (signed {ys}, {yr}yr)")

    js = "// AUTO-GENERATED by scripts/contract_status.py — 2026 walk-year / just-signed status + value bump.\n" \
         "const CONTRACT_STATUS = " + json.dumps(status, separators=(",", ":")) + ";\n"
    for d in (os.path.join(ROOT, "docs"), os.path.join(ROOT, "outputs", "draft_tool")):
        try: open(os.path.join(d, "contract_status.js"), "w", encoding="utf-8").write(js)
        except OSError: pass
    print(f"\nWrote docs/contract_status.js ({len(status)} players)")


if __name__ == "__main__":
    main()
