"""
Healthy-baseline PPG for injury-shortened players.

A player who missed most of 2025 gets a projected per-game rate anchored on that lost season
(e.g. Joe Burrow projects 17.1 PPG though he scored 27.8 in a healthy 2024). This computes each
player's league-scored PPG for 2024 and 2025 from nfl_data_py game logs, flags players whose
2025 was injury-shortened, and emits a BLENDED healthy rate (docs/healthy_ppg.js) that the board
and the keeper predictor use to value them on their true level instead of the injury year.

League scoring: 6pt pass TD, 0.04/pass yd, -1 INT, 0.1/rush+rec yd, 6 rush/rec TD, 1/reception
(full PPR), 2pt=2, -1 per fumble lost.

Run:  python scripts/healthy_ppg.py     (writes docs/healthy_ppg.js + outputs/draft_tool copy)
"""
import os, json, re
import nfl_data_py as nfl

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
norm = lambda s: re.sub(r"\b(jr|sr|ii|iii|iv|v)\b", "", re.sub(r"[^a-z ]", "", str(s).lower())).replace("  ", " ").strip()
BLEND = 0.5          # weight on the healthy 2024 rate vs the (depressed) model rate
MIN_2024_G = 10      # needs a substantial healthy 2024 to anchor on
MIN_2024_PPG = 8.0   # ...and to have been a real contributor (skip deep scrubs)
MAX_2025_G = 12      # 2025 counts as injury-shortened at/under this many implied games played


def season_ppg(year):
    try:
        w = nfl.import_weekly_data([year])
    except Exception as e:
        print(f"  ({year} weekly unavailable: {e}) — proceeding without it")
        return {}
    w = w[w["season_type"] == "REG"].copy()
    cols = ["passing_yards", "passing_tds", "interceptions", "rushing_yards", "rushing_tds",
            "receptions", "receiving_yards", "receiving_tds", "passing_2pt_conversions",
            "rushing_2pt_conversions", "receiving_2pt_conversions", "sack_fumbles_lost",
            "rushing_fumbles_lost", "receiving_fumbles_lost"]
    for c in cols:
        if c not in w.columns: w[c] = 0
    w[cols] = w[cols].fillna(0)
    fp = (w["passing_yards"] * 0.04 + w["passing_tds"] * 6 + w["interceptions"] * -1
          + w["rushing_yards"] * 0.1 + w["rushing_tds"] * 6
          + w["receptions"] * 1 + w["receiving_yards"] * 0.1 + w["receiving_tds"] * 6
          + (w["passing_2pt_conversions"] + w["rushing_2pt_conversions"] + w["receiving_2pt_conversions"]) * 2
          + (w["sack_fumbles_lost"] + w["rushing_fumbles_lost"] + w["receiving_fumbles_lost"]) * -1)
    w = w.assign(fp=fp)
    out = {}
    for nm, grp in w.groupby("player_display_name"):
        g = len(grp)
        if g: out[norm(nm)] = {"ppg": grp["fp"].sum() / g, "g": g}
    return out


def main():
    P = json.loads(open(os.path.join(ROOT, "docs", "data.js"), encoding="utf-8").read()
                   .split("const PLAYERS = ")[1].rsplit(";", 1)[0])
    y24 = season_ppg(2024)
    # implied 2025 games = 2025 total (actual_2025) / 2025 per-game rate (prior_ppg) — the injury signal
    healthy, rows = {}, []
    for p in P:
        if p.get("is_rookie") or p["position"] not in ("QB", "RB", "WR", "TE"): continue
        a = y24.get(norm(p["name"]))
        if not a or a["g"] < MIN_2024_G or a["ppg"] < MIN_2024_PPG: continue   # healthy, real 2024
        proj = p.get("proj_ppg") or 0
        if a["ppg"] <= proj: continue                            # only lift, never lower
        a25, pp25 = p.get("actual_2025"), p.get("prior_ppg")
        if not a25 or not pp25 or a25 <= 0 or pp25 <= 0: continue
        g25 = a25 / pp25                                         # implied 2025 games played
        if g25 < 1 or g25 > MAX_2025_G: continue                 # <1 = bad data; >MAX = played most of 2025
        rate = round(BLEND * a["ppg"] + (1 - BLEND) * proj, 1)
        healthy[p["name"]] = rate
        rows.append((p["name"], p["position"], round(proj, 1), round(a["ppg"], 1), a["g"], round(g25, 1), rate))
    rows.sort(key=lambda r: -(r[6] - r[2]))
    print(f"Flagged {len(rows)} injury-return players (healthy 2024, injury-shortened 2025, depressed rate):")
    print("  %-22s %-3s  proj  2024ppg  g24  ~g25  -> blended" % ("player", "pos"))
    for nm, pos, proj, p24, g24, g25, rate in rows:
        print("  %-22s %-3s  %4.1f  %5.1f    %3d  %4.1f  -> %.1f" % (nm[:22], pos, proj, p24, g24, g25, rate))
    js = "// AUTO-GENERATED by scripts/healthy_ppg.py — blended healthy PPG for injury-return players.\n" \
         "const HEALTHY_PPG = " + json.dumps(healthy, separators=(",", ":")) + ";\n"
    for d in (os.path.join(ROOT, "docs"), os.path.join(ROOT, "outputs", "draft_tool")):
        try: open(os.path.join(d, "healthy_ppg.js"), "w", encoding="utf-8").write(js)
        except OSError: pass
    print(f"\nWrote docs/healthy_ppg.js ({len(healthy)} players)")


if __name__ == "__main__":
    main()
