"""
Bake ESPN Live Draft Trends salaries (user CSV export from the ESPN homepage) into
docs/espn_salary_2026.js for the draft tool's ESPN price modes.

CSV shape: Rank, Player ("Name\nTEAMPOS" in one quoted cell), AVG PICK, 7d, AVG SALARY, 7d, %ROST.
Emits ESPN_SALARY_RAW = [[name, pos, avg_salary], ...] — index.html builds the fkey map
so JS-side name normalization stays the single source of truth.

Usage: python scripts/import_espn_salaries.py [path-to-csv]   (default data/espn_salaries_2026.csv)
"""
import csv, json, os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "data", "espn_salaries_2026.csv")
POS = re.compile(r"(QB|RB|WR|TE|K|D/ST)$")
rows, skipped = [], []
for r in csv.DictReader(open(src, encoding="utf-8-sig")):
    cell = (r.get("Player") or "").strip()
    lines = [x.strip() for x in cell.split("\n") if x.strip()]
    try:
        sal = float(r.get("AVG SALARY") or 0)
    except ValueError:
        sal = 0
    tag = lines[-1].split(",")[0].strip() if len(lines) >= 2 else ""   # "JAXWR, CB" -> "JAXWR" (two-way players)
    m = POS.search(tag)
    if not m or sal <= 0:
        skipped.append(cell.replace("\n", " / "))
        continue
    pos = "DST" if m.group(1) == "D/ST" else m.group(1)
    # strip ESPN's injury-status suffix glued onto the name ("Ja'Marr ChaseQ")
    nm = re.sub(r"(?<=[a-z.'])(?:IR|SSPD|PUP|NFI|[QODP])$", "", lines[0])
    rows.append([nm, pos, sal])
js = ("// AUTO-GENERATED by scripts/import_espn_salaries.py from an ESPN Live Draft Trends CSV\n"
      "// export (data/espn_salaries_2026.csv) — sitewide average auction salaries, the PUBLIC\n"
      "// price benchmark. index.html maps names via fkey() at load.\n"
      "const ESPN_SALARY_RAW = " + json.dumps(rows, separators=(",", ":")) + ";\n")
for d in ("docs", os.path.join("outputs", "draft_tool")):
    open(os.path.join(ROOT, d, "espn_salary_2026.js"), "w", encoding="utf-8").write(js)
print(f"{len(rows)} salaries baked ({len(skipped)} rows skipped)")
for s in skipped[:6]: print("  skipped:", s[:70])
