"""
FANTASY-PLAYOFF SOS 2026 - who has the soft weeks 14-17?

2026 schedule (data/schedule_2026.csv, habitatring/nflverse) x 2025 positional
fantasy-points-allowed (nflv_weekly, opponent_team). For each NFL team, rate the
weeks 14-17 slate per position:

  FPA_pos(def) = 2025 mean PPR points that defense allowed per game to the
  position, z-scored across defenses. Slate score = mean over wks 14-17
  opponents (+ = generous slate). Roof: playoff-week outdoor cold-weather
  sites noted (context only - wind kills deep passing, see wind study).

CAVEAT (stated in the report): 2025 defense is a noisy proxy for 2026 defense
(year-over-year FPA correlation is weak); treat as a TIEBREAKER between
otherwise-close draft targets, never a primary signal.

Output: outputs/reports/playoff_sos_2026.md + docs/playoff_sos_2026.js
"""
import os, json
import numpy as np, pandas as pd
import sqlite3

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CAN = {"GNB": "GB", "KAN": "KC", "LVR": "LV", "OAK": "LV", "NOR": "NO", "NWE": "NE", "SFO": "SF",
       "TAM": "TB", "SD": "LAC", "STL": "LAR", "LA": "LAR", "WSH": "WAS", "JAC": "JAX"}
can = lambda t: CAN.get(t, t)

con = sqlite3.connect(os.path.join(ROOT, "db", "nfl_odds.db"))
W = pd.read_sql("""SELECT position, season, week, team, opponent_team opp, fantasy_points_ppr pts
                   FROM nflv_weekly WHERE season=2025 AND season_type='REG'
                     AND position IN ('QB','RB','WR','TE')""", con)
con.close()
W["opp"] = W.opp.map(can); W["team"] = W.team.map(can)
# points allowed per defense per position per game
fpa = W.groupby(["opp", "position", "week"]).pts.sum().reset_index() \
       .groupby(["opp", "position"]).pts.mean().rename("fpa").reset_index()
fpa["z"] = fpa.groupby("position").fpa.transform(lambda s: (s - s.mean()) / s.std())

S = pd.read_csv(os.path.join(ROOT, "data", "schedule_2026.csv"))
S = S[(S.game_type == "REG") & S.week.between(14, 17)]
S["home_team"] = S.home_team.map(can); S["away_team"] = S.away_team.map(can)
slate = {}
for _, g in S.iterrows():
    slate.setdefault(g.home_team, []).append((int(g.week), g.away_team, g.roof))
    slate.setdefault(g.away_team, []).append((int(g.week), g.home_team, g.roof))

Z = fpa.set_index(["opp", "position"])["z"]
rows = []
for tm, opps in slate.items():
    r = {"team": tm, "opps": "/".join(f"w{w}:{o}" for w, o, _ in sorted(opps))}
    for pos in ("QB", "RB", "WR", "TE"):
        zs = [Z.get((o, pos), np.nan) for _, o, _ in opps]
        r[pos] = float(np.nanmean(zs))
    r["outdoor_dec"] = sum(1 for _, o, roof in opps if str(roof) in ("outdoors", "open"))
    rows.append(r)
R = pd.DataFrame(rows).set_index("team")

_out = []
def pr(*a): s = " ".join(str(x) for x in a); _out.append(s); print(s)

pr("weeks 14-17 slate generosity by position (z of 2025 FPA; + = soft slate)\n")
for pos in ("QB", "RB", "WR", "TE"):
    top = R[pos].sort_values(ascending=False)
    pr(f"{pos}: best  " + "  ".join(f"{t} {v:+.2f}" for t, v in top.head(5).items()))
    pr(f"{pos}: worst " + "  ".join(f"{t} {v:+.2f}" for t, v in top.tail(5).items()))
pr("\nmost outdoor December games (wind/cold risk, context only): " +
   ", ".join(f"{t}({int(v)})" for t, v in R.outdoor_dec.sort_values(ascending=False).head(8).items()))
pr("\nfull table (z by position):")
pr(R[["QB", "RB", "WR", "TE", "outdoor_dec"]].round(2).sort_values("RB", ascending=False).to_string())

open(os.path.join(ROOT, "outputs", "reports", "playoff_sos_2026.md"), "w", encoding="utf-8").write(
    "# Fantasy-playoff SOS 2026 (weeks 14-17)\n\n"
    "Generated by `scripts/playoff_sos_study.py`. Opponent generosity = 2025 positional\n"
    "fantasy-points-allowed, z-scored. **2025 defense is a noisy proxy for 2026 - use as\n"
    "a tiebreaker between close targets only.**\n\n```\n" + "\n".join(_out) + "\n```\n")

# bye weeks from the schedule: a team absent from week W's slate is on bye
SF = pd.read_csv(os.path.join(ROOT, "data", "schedule_2026.csv"))
SF = SF[SF.game_type == "REG"]
SF["home_team"] = SF.home_team.map(can); SF["away_team"] = SF.away_team.map(can)
allteams = set(SF.home_team) | set(SF.away_team)
byes = {}
for wk, g in SF.groupby("week"):
    for t in allteams - (set(g.home_team) | set(g.away_team)):
        byes.setdefault(t, int(wk))
js = ("// AUTO-GENERATED by scripts/playoff_sos_study.py - weeks 14-17 slate generosity per\n"
      "// NFL team (z of 2025 positional FPA; + = soft playoff slate). TIEBREAKER ONLY.\n"
      "// BYES_2026: each team's bye week from the 2026 schedule.\n"
      "const PLAYOFF_SOS = " + json.dumps({t: {p: round(float(R.loc[t, p]), 2) for p in ("QB", "RB", "WR", "TE")}
                                           for t in R.index}, separators=(",", ":")) + ";\n"
      "const BYES_2026 = " + json.dumps(byes, separators=(",", ":")) + ";\n")
for d in ("docs", os.path.join("outputs", "draft_tool")):
    open(os.path.join(ROOT, d, "playoff_sos_2026.js"), "w", encoding="utf-8").write(js)
print("\nwrote outputs/reports/playoff_sos_2026.md + docs/playoff_sos_2026.js")
