"""Emit docs/rb_archetype.js — INFORMATIONAL 2025 RB archetype tags (no value change).
Gdula/4for4 thesis: pass-game specialists fade, medium-volume dual-threats are the durable profile.
Classify each RB by 2025 carries/game x targets/game (validated in scripts/rb_archetype.py: the
projection already PRICES this, so tag is context only). Source: pbp 2025 read directly (pkg gates it)."""
import warnings; warnings.filterwarnings("ignore")
import os, json, re
import pandas as pd, nfl_data_py as nfl
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REL="https://github.com/nflverse/nflverse-data/releases/download/"
norm=lambda s: re.sub(r"\s+"," ",re.sub(r"\b(jr|sr|ii|iii|iv|v)\b","",re.sub(r"[^a-z ]","",str(s).lower()))).strip()
pbp=pd.read_parquet(REL+"pbp/play_by_play_2025.parquet",
    columns=["game_id","rush_attempt","rusher_player_id","pass_attempt","receiver_player_id","season_type"])
pbp=pbp[pbp.season_type=="REG"]
rush=pbp[(pbp.rush_attempt==1)&pbp.rusher_player_id.notna()]
rec =pbp[(pbp.pass_attempt==1)&pbp.receiver_player_id.notna()]
car=rush.groupby("rusher_player_id").size().rename("car")
tgt=rec.groupby("receiver_player_id").size().rename("tgt")
# games played ~ distinct games appearing as rusher or receiver
g=pd.concat([rush[["rusher_player_id","game_id"]].rename(columns={"rusher_player_id":"pid"}),
             rec[["receiver_player_id","game_id"]].rename(columns={"receiver_player_id":"pid"})])
games=g.drop_duplicates().groupby("pid").size().rename("g")
pl=nfl.import_players()[["gsis_id","display_name","position"]]
nm=dict(zip(pl.gsis_id,pl.display_name)); ps=dict(zip(pl.gsis_id,pl.position))
P=json.loads(open(os.path.join(ROOT,"docs","data.js"),encoding="utf-8").read().split("const PLAYERS = ")[1].rsplit(";",1)[0])
canon={norm(p["name"]):p["name"] for p in P if p.get("position")=="RB"}
df=pd.concat([car,tgt,games],axis=1).fillna(0); df=df[df.g>=6]
def cls(cpg,tpg):
    if cpg>=15: return "high"
    if cpg>=8.5: return "med_dt" if tpg>=2.5 else "med"
    return "spec" if tpg>=3 else "low"
out={}
for pid,r in df.iterrows():
    if ps.get(pid)!="RB": continue
    cn=canon.get(norm(nm.get(pid,"")))
    if not cn: continue
    cpg,tpg=r.car/r.g,r.tgt/r.g; a=cls(cpg,tpg)
    if a=="low": continue
    out[cn]={"a":a,"cpg":round(cpg,1),"tpg":round(tpg,1)}
lab={"high":"High-vol","med_dt":"Medium dual-threat","med":"Medium rush","spec":"Pass-specialist risk"}
from collections import Counter; c=Counter(v["a"] for v in out.values())
print("2025 RB archetypes:",{lab[k]:c[k] for k in c})
for cn,d in sorted(out.items(),key=lambda x:(x[1]["a"]!="spec",x[1]["a"]!="med_dt",-x[1]["cpg"]))[:14]:
    print(f"   {lab[d['a']]:22s} {cn:22s} {d['cpg']} car/g  {d['tpg']} tgt/g")
js=("// AUTO-GENERATED by scripts/rb_archetype_tag.py — INFORMATIONAL 2025 RB archetype (no value change).\n"
    "// Gdula/4for4 thesis; validated in scripts/rb_archetype.py (projection already prices car/g x tgt/g).\n"
    "const RB_ARCH = "+json.dumps(out,separators=(",",":"))+";\n")
for d in (os.path.join(ROOT,"docs"),os.path.join(ROOT,"outputs","draft_tool")):
    try: open(os.path.join(d,"rb_archetype.js"),"w",encoding="utf-8").write(js)
    except OSError: pass
print(f"\nWrote docs/rb_archetype.js ({len(out)} RBs)")
