"""
WINNING ROSTERS - what did this league's successful builds look like?

espn_drafts.csv x espn_standings.csv (2023-25, 35 team-seasons). For every
team-season: draft-day budget shape (keepers included at their cost) vs final
finish (rank_final; playoff = top 6).

Shape metrics:
  top1_share / top2_share   budget concentration on the most expensive players
  n_20plus                  players bought at $20+
  n_dollar                  $1-3 lottery picks
  pos_share                 QB / RB / WR / TE budget split
  keeper_surplus            sum over keeps of (same-season FFA AAV - cost)

Output: outputs/reports/winning_rosters.md
"""
import os, re
import numpy as np, pandas as pd
import sqlite3

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
norm = lambda s: re.sub(r"\s+", " ", re.sub(r"\b(jr|sr|ii|iii|iv|v)\b", "",
                        re.sub(r"[^a-z ]", "", str(s).lower()))).strip()

dr = pd.read_csv(os.path.join(ROOT, "outputs", "espn_drafts.csv"))
st = pd.read_csv(os.path.join(ROOT, "outputs", "espn_standings.csv"))
dr["kept"] = dr.keeper.astype(str).str.lower().isin(["true", "1"])
dr["bid"] = pd.to_numeric(dr.bid, errors="coerce").fillna(0).clip(lower=1)
dr["nm"] = dr.player.map(norm)
con = sqlite3.connect(os.path.join(ROOT, "db", "nfl_odds.db"))
ffa = pd.read_sql("SELECT season, player, ffa_aav FROM nflv_ffa_league WHERE ffa_aav IS NOT NULL", con)
con.close()
ffa["nm"] = ffa.player.map(norm); ffa = ffa.drop_duplicates(["season", "nm"])
dr = dr.merge(ffa[["season", "nm", "ffa_aav"]], on=["season", "nm"], how="left")

rows = []
for (season, owner), g in dr.groupby(["season", "owner"]):
    tot = g.bid.sum()
    if tot < 100: continue                       # partial data guard
    gs = g.sort_values("bid", ascending=False)
    sk = g[g.pos.isin(["QB", "RB", "WR", "TE"])]
    kp = g[g.kept]
    rows.append(dict(
        season=season, owner=owner, total=tot,
        top1=gs.bid.iloc[0] / tot, top2=gs.bid.iloc[:2].sum() / tot,
        top3=gs.bid.iloc[:3].sum() / tot,
        n20=(g.bid >= 20).sum(), n_dollar=(g.bid <= 3).sum(),
        qb_sh=sk[sk.pos == "QB"].bid.sum() / max(sk.bid.sum(), 1),
        rb_sh=sk[sk.pos == "RB"].bid.sum() / max(sk.bid.sum(), 1),
        wr_sh=sk[sk.pos == "WR"].bid.sum() / max(sk.bid.sum(), 1),
        te_sh=sk[sk.pos == "TE"].bid.sum() / max(sk.bid.sum(), 1),
        k_surplus=(kp.ffa_aav.fillna(kp.bid) - kp.bid).sum(),
        n_keep=len(kp)))
R = pd.DataFrame(rows).merge(
    st[["season", "owner", "rank_final", "points_for", "wins"]], on=["season", "owner"], how="inner")
R["playoff"] = R.rank_final <= 6
R["top3fin"] = R.rank_final <= 3

_out = []
def pr(*a): s = " ".join(str(x) for x in a); _out.append(s); print(s)

pr(f"team-seasons matched: {len(R)} (2023-25)\n")
pr("mean by finish bucket:")
cols = ["top1", "top2", "top3", "n20", "n_dollar", "qb_sh", "rb_sh", "wr_sh", "te_sh", "k_surplus", "n_keep"]
buckets = [("champ+2nd+3rd", R.top3fin), ("playoff (top6)", R.playoff), ("missed (7-12)", ~R.playoff)]
pr(f"{'':16s}" + "".join(f"{c:>9s}" for c in cols))
for lbl, m in buckets:
    g = R[m]
    pr(f"{lbl:16s}" + "".join(f"{g[c].mean():9.2f}" for c in cols))

pr("\nSpearman vs final rank (negative = MORE of it -> BETTER finish):")
from scipy import stats
for c in cols + ["total"]:
    rho, p = stats.spearmanr(R[c], R.rank_final)
    star = " *" if p < 0.10 else ""
    pr(f"  {c:10s} rho {rho:+.2f} (p={p:.3f}){star}")

pr("\nchampionship rosters (rank 1):")
for _, r in R[R.rank_final == 1].iterrows():
    g = dr[(dr.season == r.season) & (dr.owner == r.owner)].sort_values("bid", ascending=False)
    top = ", ".join(f"{x.player} ${x.bid:.0f}{'(K)' if x.kept else ''}" for _, x in g.head(4).iterrows())
    pr(f"  {r.season} {str(r.owner)[:16]:16s} top2 {r.top2:.0%} | $20+ x{r.n20} | $1-3 x{r.n_dollar} "
       f"| keeper surplus ${r.k_surplus:+.0f} | {top}")

open(os.path.join(ROOT, "outputs", "reports", "winning_rosters.md"), "w", encoding="utf-8").write(
    "# Winning rosters - budget shapes vs finish in this league (2023-25)\n\n"
    "Generated by `scripts/winning_rosters_study.py`. n=35 team-seasons - read\n"
    "directions, not decimals.\n\n```\n" + "\n".join(_out) + "\n```\n")
print("\nwrote outputs/reports/winning_rosters.md")
